/**
 * @license Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.html or http://ckeditor.com/license
 */

var CKBUILDER_CONFIG = {
	skin: 'moono',
	ignore: [
		'dev',
		'README.md',
		'.gitignore',
		'.gitattributes',
		'.idea',
		'.mailmap',
		'.DS_Store',
		'samples'
	],
	plugins: {
		a11yhelp: 1,
		autogrow: 1,
		basicstyles: 1,
		bidi: 1,
		blockquote: 1,
		clipboard: 1,
		colorbutton: 1,
		colordialog: 1,
		contextmenu: 1,
		dialogadvtab: 1,
		elementspath: 1,
		enterkey: 1,
		entities: 1,
		fakeobjects: 1,
		find: 1,
		flash: 1,
		floatingspace: 1,
		font: 1,
		format: 1,
		horizontalrule: 1,
		htmlwriter: 1,
		image: 1,
		indent: 1,
		justify: 1,
		link: 1,
		list: 1,
		liststyle: 1,
		magicline: 1,
		newpage: 1,
		pagebreak: 1,
		pastefromword: 1,
		pastetext: 1,
		removeformat: 1,
		save: 1,
		selectall: 1,
		sharedspace: 1,
		showblocks: 1,
		showborders: 1,
		sourcearea: 1,
		specialchar: 1,
		stylescombo: 1,
		tab: 1,
		table: 1,
		tableresize: 1,
		tabletools: 1,
		toolbar: 1,
		undo: 1,
		wysiwygarea: 1,
		// mindtouch plugins
		'mt-autogrow': 1,
		'mt-autosave': 1,
		'mt-ckoverrides': 1,
		'mt-clearcontents': 1,
		'mt-clipboard': 1,
		'mt-commentdelete': 1,
		'mt-dialog': 1,
		'mt-elementbubble': 1,
		'mt-format': 1,
		'mt-floatingtoolbar': 1,
		'mt-image': 1,
		'mt-imageattach': 1,
		'mt-imageresize': 1,
		'mt-infobar': 1,
		'mt-infopanel': 1,
		'mt-keystrokes': 1,
		'mt-link': 1,
		'mt-misc': 1,
		'mt-pre': 1,
		'mt-richcombomenu': 1,
		'mt-save': 1,
		'mt-statistics': 1,
		'mt-stylescombomenu': 1,
		'mt-stylewrap': 1,
		'mt-storage': 1,
		'mt-table': 1,
		'mt-tableadvanced': 1,
		'mt-templates': 1,
		'mt-tools': 1,
		'mt-transformations': 1,
		'mt-video': 1,
		'mt-viewmenu': 1,
		'mt-whoisediting': 1,
		'definitionlist': 1
		'zeroclipboard': 1
	}
};
