/**
 * @license Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.html or http://ckeditor.com/license
 */

var CKBUILDER_CONFIG = {
	skin: 'mindtouch',
	ignore: [
		'dev',
		'README.md',
		'.gitignore',
		'.gitattributes',
		'.gitmodules',
		'.idea',
		'.mailmap',
		'.DS_Store',
		'samples'
	],
	plugins: {
		a11yhelp: 1,
		autogrow: 1,
		basicstyles: 1,
		bidi: 1,
		blockquote: 1,
		clipboard: 1,
		colorbutton: 1,
		colordialog: 1,
		contextmenu: 1,
		dialogadvtab: 1,
		elementspath: 1,
		enterkey: 1,
		entities: 1,
		fakeobjects: 1,
		find: 1,
		flash: 1,
		floatingspace: 1,
		font: 1,
		format: 1,
		horizontalrule: 1,
		htmlwriter: 1,
		image: 1,
		indent: 1,
		justify: 1,
		link: 1,
		list: 1,
		liststyle: 1,
		magicline: 1,
		menubutton: 1,
		newpage: 1,
		pagebreak: 1,
		pastefromword: 1,
		pastetext: 1,
		removeformat: 1,
		save: 1,
		selectall: 1,
		sharedspace: 1,
		showblocks: 1,
		showborders: 1,
		sourcearea: 1,
		specialchar: 1,
		stylescombo: 1,
		tab: 1,
		table: 1,
		tableresize: 1,
		tabletools: 1,
		toolbar: 1,
		undo: 1,
		wysiwygarea: 1,
		onchange: 1,
		scayt: 1,
		'mindtouch/autogrow': 1,
		'mindtouch/autosave': 1,
		'mindtouch/ckoverrides': 1,
		'mindtouch/clearcontents': 1,
		'mindtouch/clipboard': 1,
		'mindtouch/commentdelete': 1,
		'mindtouch/definitionlist': 1,
		'mindtouch/dialog': 1,
		'mindtouch/elementbubble': 1,
		'mindtouch/enterkey': 1,
		'mindtouch/extensions': 1,
		'mindtouch/format': 1,
		'mindtouch/floatingtoolbar': 1,
		'mindtouch/image': 1,
		'mindtouch/imageattach': 1,
		'mindtouch/imageresize': 1,
		'mindtouch/infobar': 1,
		'mindtouch/infopanel': 1,
		'mindtouch/keystrokes': 1,
		'mindtouch/link': 1,
		'mindtouch/misc': 1,
		'mindtouch/pre': 1,
		'mindtouch/richcombomenu': 1,
		'mindtouch/save': 1,
		'mindtouch/scaytcustom': 1,
		'mindtouch/statistics': 1,
		'mindtouch/stylescombomenu': 1,
		'mindtouch/stylewrap': 1,
		'mindtouch/storage': 1,
		'mindtouch/table': 1,
		'mindtouch/tableclipboard': 1,
		'mindtouch/tablehandlers': 1,
		'mindtouch/templates': 1,
		'mindtouch/transformations': 1,
		'mindtouch/video': 1,
		'mindtouch/viewmenu': 1,
		'mindtouch/whoisediting': 1,
		'mindtouch/zeroclipboard': 1
	},
	js: [
		'../../plugins/mindtouch/video/js/sly.min.js',
		'../../plugins/mindtouch/zeroclipboard/ZeroClipboard.min.js'
	]
};
